githubUsername: khebbie
gravatarEmail: klaus@hebsgaard.dk
development:
  redisUrl: redis://localhost:6379/
production:
  redisUrl: redis://redistogo:044be3cb6f2719b29e101ce8bd680ca7@spadefish.redistogo.com:9915/
