githubUsername: khebbie
twitterUsername: khebbie
gravatarEmail: klaus@hebsgaard.dk
redisUrl:
  development: redis://localhost:6379/
  production: redis://redistogo:044be3cb6f2719b29e101ce8bd680ca7@spadefish.redistogo.com:9915/
